### PR TITLE
docs: add syntax highlighting and fix several problems from markdownlint

### PR DESCRIPTION
**Pull request by caesariodito**
fix: 
- hard tabs ([MD010](https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md010.md))
- fenced code ([MD040](https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md040.md)) 
- trailing space ([MD009](https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md009.md)) 
- no blank line before and after heading ([MD022](https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md022.md)) 
- multiple consecutive blank lines ([MD012](https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md012.md))

### CODE REVIEW

**Comment by vianneynara** [comment]
Much appreciated, the hard tabs has been making the codes look weird. Did you do it all manually for the hard tabs?

**Comment by caesariodito** [comment]
I see, can I see the screenshot details? Yes, I did all manually, I think I have used a different indentation size compared to the source

**Comment by vianneynara** [comment]
It appeared to be normal in Obsidian and other text editors, but GitHub previews make it look wider.

**Comment by caesariodito** [comment]
Okay, so it's all good?

**Comment by vianneynara** [comment]
Guess so, but we'll use this and see the difference. Thanks for the contribution, I'll be merging this.

**Comment by vianneynara** [comment]
I'll check it out later, I'm eating rn

**Pull request merged**
